_G.Settings = {
    antilag = false,
    balckscreen = false,
    ReduceDamage = false,
    FPSGPU = fades,
    Autoleave = false,
    kickrejoin = false,
    LeaveDungeons = false,
    SummerEvent = false,
    SummerSpin = false,
    farmraidtoken = false,
    skilldelay = 1,
    distance = 10,
    toggleguikey = "z",
    afkandraid = false,
    autospingem = false,
    autoclaimrewardraid = false,
    eggspintime = "3",
    autoclaimrewardspeed = false,
    equipselectmain = false,
    equipselectmain1 = false,
    equipselectmain2 = false,
    Autoclaimquest = false,
    AutoEquipMCharacter = false,
    AutoEquipACharacter = false,
    SelectedMainCharacter = "None",
    SelectedMainCharacter = "None",
    SelectedMainCharacter = "None",
    autosellcommon = false,
    autoselluncommon = false,
    autosellrare = false,
    autosellepic = false,
    selectegg = "None",
    autoselllegendary = false,
    autoequipbest = true,
    autoupgrade = false,
    Height = 20,
    Height1 = -20,
    otherds = "@here",
    dsuser = "Not Set",
    AutoPunch = true,
    punchdelay = "4",
    webhookspeed = "10",
    AutoFarm = false,
    AutoTP = false,
    AutoTP1 = false,
    AutoTP2 = true,
    AutoRetry = false,
    webhookurl = "",
    AutoSkill1 = true,
    AutoSkill2 = true,
    AutoSkill3 = true,
    AutoSkill4 = true,
    AutoSkill5 = true,
    AutoSkill6 = true,
    kickwebhook = false,
    Speed = 80,
    Hidename = false,
    Autolvl = false,
    webhook = false,
    raidwebhook = false,
    kickrejoin = true
}
if game.PlaceId == 6938803436 or game.PlaceId == 7338881230 or game.PlaceId == 6990129309 or game.PlaceId == 7274690025 or game.PlaceId == 6990131029 or game.PlaceId == 6990133340 then
    pcall(function()
           loadstring(game:HttpGet("https://github.com/lifaiossama/errors/blob/main/Krnl.lua"))()
    end)
end